stages:
  - build
  - deploy

build artifact:
  stage: build
  before_script:
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    when: always
  rules:
    - if: '$CI_COMMIT_REF_NAME == "client"'
      when: always

deploy s3:
  stage: deploy
  before_script:
    - pip install awscli  
    - aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
    - aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
    - aws configure set default_region_name "$AWS_DEFAULT_REGION"

  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp dist s3://$S3_BUCKET --recursive
  rules:
    - if: '$CI_COMMIT_REF_NAME == "client"'
      when: always